language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
# command to install dependencies
install:
  - "pip install ."
  - "pip install coveralls"
  - "bash scripts/install-linters.sh"
# command to run tests
before_script:
  - export PATH=$PATH:$PWD/pmd-bin/bin
script: "python -R setup.py nosetests"
after_success:
  coveralls
